# Copyright 2022 Stefano Cottafavi <stefano.cottafavi@gmail.com>.
# SPDX-License-Identifier: GPL-2.0-only

name: 'KiCad publish plugin'
description: 'Publish a plugin to the official KiCad repository'

inputs:
  tag:
    type: string
    description: Tag to release
    default: "v0.0.0"

  files:
    description: 'Plugin files (to move into "plugins" folder)'
    required: false
    default: '*.py *.png'
  icon:
    description: 'Icon file'
    required: false
    default: 'assets/icon.png'
  deploy:
    type: boolean
    description: Deploy to KiCad repo
    default: false
  gitlab_user:
    description: 'GitLab username'
    required: false
    default: "${{github.actor}}"
  gitlab_branch:
    description: 'GitLab branch'
    default: "${{ github.event.repository.name }}"
  gitlab_token_name:
    description: 'GitLab token name'
    default: "github"
  gitlab_token_secret:
    description: 'GitLab token secret'
    default: "glpat-qyzaZ_s_FbqL6Rx2V2WG"

outputs:
  time: # id of output
    description: 'The time we greeted you'

runs:
  using: 'composite'
  steps:
    - name: Set env
      run: |
        echo "RELEASE_VERSION=${{inputs.tag}}" >> $GITHUB_ENV
        echo "PACKAGE_NAME=${{ github.event.repository.name }}-pcm.zip" >> $GITHUB_ENV
        echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Prepare folders
      run: |
        mkdir plugins resources
        mv ${{inputs.files}} plugins
        mv ${{inputs.icon}} resources
        zip -r ${{env.PACKAGE_NAME}} plugins resources metadata.json
      shell: bash

    - name: Update metadata (package)
      run: |
        tmp=$(mktemp)
        jq '.versions[0].download_url = "${{github.server_url}}/${{github.repository}}/releases/download/${{env.RELEASE_VERSION}}/${{env.PACKAGE_NAME}}"' metadata.json > "$tmp"
        mv "$tmp" metadata.json
      shell: bash

    - name: Get statistics
      run: |
        echo "FILE_SHA=$(shasum -a 256 ${{env.PACKAGE_NAME}} | cut -d ' ' -f1)" >> $GITHUB_ENV
        echo "FILE_SIZE=$(wc -c < ${{env.PACKAGE_NAME}})" >> $GITHUB_ENV
        echo "FILE_SIZE_UC=$(unzip -l ${{env.PACKAGE_NAME}} | tail -1 | xargs | cut -d ' ' -f1)" >> $GITHUB_ENV
      shell: bash

    - name: Update metadata (metadata repository)
      run: |
        tmp=$(mktemp)
        jq '.versions[0] += {"download_sha256": "${{ env.FILE_SHA }}", "download_size": ${{ env.FILE_SIZE }}, "install_size": ${{ env.FILE_SIZE_UC }} }' metadata.json > "$tmp"
        mv "$tmp" metadata.json
      shell: bash
    
    - name: Clone GitLab repository
      if: inputs.deploy == 'true'
      run: echo "${{ inputs }}"
      shell: bash